# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
  - [142,110, 192,243, 459,401]  # P5/32

# yolov7_MY backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
  
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2      
   [-1, 1, Conv, [64, 3, 1]],
   
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4
   [-1, 1, ELAN, [256]],  # 4-P2/4

   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 9-P3/8
   [-1, 1, ELAN, [512]],  # 10-P2/4

   [-1, 1, MP, []],
   [-1, 1, Conv, [256, 1, 1]],
   [-3, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 15-P4/16
   [-1, 1, ELAN, [1024]],  # 16-P2/4

   [-1, 1, MP, []],
   [-1, 1, Conv, [512, 1, 1]],
   [-3, 1, Conv, [512, 1, 1]],
   [-1, 1, Conv, [512, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 21-P5/32
   [-1, 1, ELAN, [1024, 2]],  # 22-P2/4

  ]

# yolov7_MY head
head:
  [[-1, 1, SPPCSPC, [512]], # 23
  
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [16, 1, Conv, [256, 1, 1]], # route backbone P4
   [[-1, -2], 1, Concat, [1]],
   [-1, 1, ELAN_H, [256]], # 28
#   [-1, 1, Conv, [256, 1, 1]],
#   [-2, 1, Conv, [256, 1, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
#   [-1, 1, Conv, [256, 1, 1]], # 35
   
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [10, 1, Conv, [128, 1, 1]], # route backbone P3
   [[-1, -2], 1, Concat, [1]],
   [-1, 1, ELAN_H, [128]], # 33
#   [-1, 1, Conv, [128, 1, 1]],
#   [-2, 1, Conv, [128, 1, 1]],
#   [-1, 1, Conv, [64, 3, 1]],
#   [-1, 1, Conv, [64, 3, 1]],
#   [-1, 1, Conv, [64, 3, 1]],
#   [-1, 1, Conv, [64, 3, 1]],
#   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
#   [-1, 1, Conv, [128, 1, 1]], # 47
      
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],
   [[-1, -3, 28], 1, Concat, [1]],
   [-1, 1, ELAN_H, [256]], # 39
#   [-1, 1, Conv, [256, 1, 1]],
#   [-2, 1, Conv, [256, 1, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [-1, 1, Conv, [128, 3, 1]],
#   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
#   [-1, 1, Conv, [256, 1, 1]], # 60
      
   [-1, 1, MP, []],
   [-1, 1, Conv, [256, 1, 1]],
   [-3, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 2]],
   [[-1, -3, 23], 1, Concat, [1]],
   [-1, 1, ELAN_H, [512]], # 45
#   [-1, 1, Conv, [512, 1, 1]],
#   [-2, 1, Conv, [512, 1, 1]],
#   [-1, 1, Conv, [256, 3, 1]],
#   [-1, 1, Conv, [256, 3, 1]],
#   [-1, 1, Conv, [256, 3, 1]],
#   [-1, 1, Conv, [256, 3, 1]],
#   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
#   [-1, 1, Conv, [512, 1, 1]], # 73
   
   [33, 1, RepConv, [256, 3, 1]],
   [39, 1, RepConv, [512, 3, 1]],
   [45, 1, RepConv, [1024, 3, 1]],

   [[46,47,48], 1, IDetect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
