# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
  - [142,110, 192,243, 459,401]  # P5/32

# yolov7_MY backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2      
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4

   [-1, 1, ELAN, [256]],  # 4-P2/4

   [-1, 1, MP_1, [256]], # c -> c
   [-1, 1, ELAN, [512]],  # 6-P3/8

   [-1, 1, MP_1, [512]],
   [-1, 1, ELAN, [1024]],  # 8-P4/16

   [-1, 1, MP_1, [1024]],
   [-1, 1, ELAN, [1024, 2]],  # 10-P5/32

  ]

# yolov7_MY head
head:
  [[-1, 1, SPPCSPC, [512]], # 11
  
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [8, 1, Conv, [256, 1, 1]], # route backbone P4
   [[-1, -2], 1, Concat, [1]],
   [-1, 1, ELAN_H, [256]], # 16

   
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [6, 1, Conv, [128, 1, 1]], # route backbone P3
   [[-1, -2], 1, Concat, [1]],
   [-1, 1, ELAN_H, [128]], # 21

   [-1, 1, MP_2, [256]], # c->2c
   [[-1, 16], 1, Concat, [1]], # route backbone P4
   [-1, 1, ELAN_H, [256]], # 24

   [-1, 1, MP_2, [512]],
   [[-1, 11], 1, Concat, [1]], # route backbone P5
   [-1, 1, ELAN_H, [512]], # 27

   
   [21, 1, RepConv, [256, 3, 1]],
   [24, 1, RepConv, [512, 3, 1]],
   [27, 1, RepConv, [1024, 3, 1]],

   [[28,29,30], 1, IDetect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
